#!/bin/sh
# Mass DNS AXFR - developed by acidvegas in posix shell script (https://git.acid.vegas/mdaxfr)

OUTPUT_DIR="axfrout"
mkdir -p "$OUTPUT_DIR"

resolve_nameserver() {
	dig +short "$1" A || dig +short "$1" AAAA
}

attempt_axfr() {
	tld=$1
	nameserver=$2
	filename="$3"
	temp_file="${filename}.temp"

	nameserver_ip=$(resolve_nameserver "$nameserver")
	if [ -z "$nameserver_ip" ]; then
		echo "Failed to resolve nameserver $nameserver"
		return
	fi

	dig AXFR "$tld" "@$nameserver_ip" > "$temp_file"
	if [ $? -eq 0 ]; then
		mv "$temp_file" "$filename"
	else
		echo "Failed to perform zone transfer from $nameserver for $tld"
		rm -f "$temp_file"
	fi
}

# For root nameservers
for root in $(dig +short . NS); do
	attempt_axfr "." "$root" "$OUTPUT_DIR/$root-root.txt"
done

# For TLD nameservers
for tld in $(curl -s 'https://data.iana.org/TLD/tlds-alpha-by-domain.txt' | tail -n +2 | tr '[:upper:]' '[:lower:]'); do
	for ns in $(dig +short "$tld" NS); do
		attempt_axfr "$tld" "$ns" "$OUTPUT_DIR/$tld.txt"
	done
done

# For Public Suffix List TLD nameservers
for tld in $(curl -s https://publicsuffix.org/list/public_suffix_list.dat | grep -vE '^(//|.*[*!])' | grep '\.' | awk '{print $1}'); do
	for ns in $(dig +short "$tld" NS); do
		attempt_axfr "$tld" "$ns" "$OUTPUT_DIR/$tld.txt"
	done
done
