#!/bin/sh
# Mass DNS AXFR (other zones) - developed by acidvegas (https://git.acid.vegas/mdaxfr)

# https://portal.switch.ch/pub/open-data/#tab-fccd70a3-b98e-11ed-9a74-5254009dc73c-3
dig @zonedata.switch.ch ch. AXFR -y hmac-sha512:tsig-zonedata-ch-public-21-01:stZwEGApYumtXkh73qMLPqfbIDozWKZLkqRvcjKSpRnsor6A6MxixRL6C2HeSVBQNfMW4wer+qjS0ZSfiWiJ3Q== > ch.txt
dig @zonedata.switch.ch li. AXFR -y hmac-sha512:tsig-zonedata-li-public-21-01:t8GgeCn+fhPaj+cRy1epox2Vj4hZ45ax6v3rQCkkfIQNg5fsxuU23QM5mzz+BxJ4kgF/jiQyBDBvL+XWPE6oCQ== > li.txt

dig @zonedata.iis.se  se  AXFR > se.txt
dig @zonedata.iis.se  nu  AXFR > nu.txt

dig @zone.internet.ee ee. AXFR > ee.txt

dig @ns1.gov.ps xn--ygbi2ammx. AXFR > xn--ygbi2ammx.txt

wget -O sk.txt https://sk-nic.sk/subory/domains.txt

wget -O gov.txt https://raw.githubusercontent.com/cisagov/dotgov-data/main/gov.txt

wget -O nc.txt https://www.domaine.nc/whos?who=A*

# https://www.afnic.fr/produits-services/services-associes/donnees-partagees/

curl -s -H 'Accept: application/json' 'https://odata.domain.fi/OpenDomainData.svc/Domains?$inlinecount=allpages' # not sure about this one....

wget -O dn42.txt http://ix.ucis.nl/dn42/dnszone2.php? # Darknet